---

- hosts: all
  become: yes
  tasks:
  -  name: Install Zabbix-agent on RedHat Family
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd
  -  name: Install redis on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  -  name: replace line
     lineinfile:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^(.*)Server=127.0.0.1(.*)$'
       line: 'Server=158.160.34.153'
       backrefs: yes
  handlers:
  -  name: zabbix-agent systemd
     systemd:
       name: zabbix-agent.service
       enabled: yes
       state: started